yolo_model:

  config_file:
    name: yolov3-tiny-door-detection.cfg
  weight_file:
    name: yolov3-tiny-door-detection.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - door
